<?php

namespace PPRH;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class GeneralSettings {

	public $disable_wp_hints = false;

	public $html_head = false;

	public static function save_options() {
		$options = array(
			'pprh_html_head'        => ( ! empty( $_POST[ 'pprh_html_head' ] ) ? Utils::strip_non_alphanums( $_POST[ 'pprh_html_head' ] ) : 'false' ),
			'pprh_disable_wp_hints' => ( ! empty( $_POST[ 'pprh_disable_wp_hints' ] ) ? Utils::strip_non_alphanums( $_POST[ 'pprh_disable_wp_hints' ] ) : 'false' ),
		);

		Utils::update_option( 'pprh_disable_wp_hints', $options[ 'pprh_disable_wp_hints' ] );
		Utils::update_option( 'pprh_html_head', $options[ 'pprh_html_head' ] );
	}

	public function show_settings() {
		$this->set_values();
		$this->markup();
	}

	public function set_values() {
		$this->disable_wp_hints = \PPRH\Utils::does_option_match( 'pprh_disable_wp_hints', 'true', 'checked' );
		$this->html_head = \PPRH\Utils::does_option_match( 'pprh_html_head', 'true', 'checked' );
	}

	public function markup() {
		$selected = 'selected="selected"';
		?>
		<table class="form-table">
			<tbody>

			<tr>
				<th><?php esc_html_e( 'Disable automatically generated WordPress resource hints?', 'pprh' ); ?></th>

				<td>
					<input type="checkbox" name="pprh_disable_wp_hints" value="true" <?php echo $this->disable_wp_hints; ?>/>
					<p><?php esc_html_e( 'This option will remove three resource hints automatically generated by WordPress, as of 4.8.2.', 'pprh' ); ?></p>
				</td>
			</tr>

			<tr>
				<th><?php esc_html_e( 'Send resource hints in HTML head or HTTP header?', 'pprh' ); ?></th>

				<td>
					<select id="pprhHintLocation" name="pprh_html_head">
						<option value="true" <?php echo Utils::does_option_match( 'pprh_html_head', 'true', $selected ); ?>><?php esc_html_e( 'HTML &lt;head&gt;', 'pprh' ); ?></option>
						<option value="false" <?php echo Utils::does_option_match( 'pprh_html_head', 'false', $selected ); ?>><?php esc_html_e( 'HTTP Header', 'pprh' ); ?></option>
					</select>
					<p><?php esc_html_e( 'Send hints in the HTML &lt;head&gt; or the HTTP header.', 'pprh' ); ?></p>
				</td>
			</tr>

			<?php \do_action( 'pprh_sc_general_settings' ); ?>

			</tbody>
		</table>
		<?php
	}

}
