<?php

namespace PPRH;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class GeneralSettings {

	public $disable_wp_hints = false;

	public $html_head = false;

//	public function __construct() {}

	public function save_options() {

	    $options = array(
            'pprh_html_head'        => ( ! empty( $_POST['pprh_html_head'] ) ? Utils::strip_non_alphanums( $_POST['pprh_html_head'] ) : 'false' ),
			'pprh_disable_wp_hints' => ( ! empty( $_POST['pprh_disable_wp_hints'] ) ? Utils::strip_non_alphanums( $_POST['pprh_disable_wp_hints'] ) : 'false' ),
		);

		update_option('pprh_disable_wp_hints', $options['pprh_disable_wp_hints'] );
		update_option('pprh_html_head', $options['pprh_html_head'] );
	}

	public function show_settings() {
		$this->set_values();
		$this->markup();
	}

	public function set_values() {
		$this->disable_wp_hints = \PPRH\Utils::is_option_checked( 'pprh_disable_wp_hints' );
		$this->html_head = \PPRH\Utils::is_option_checked( 'pprh_html_head' );
	}

	public function markup() {
		?>
		<div class="postbox" id="general">
			<div class="inside">
				<h3><?php esc_html_e( 'General Settings', 'pprh' ); ?></h3>

				<table class="form-table">
					<tbody>

					<tr>
						<th><?php esc_html_e( 'Disable automatically generated WordPress resource hints?', 'pprh' ); ?></th>

						<td>
							<input type="checkbox" name="pprh_disable_wp_hints" value="true" <?php echo $this->disable_wp_hints; ?>/>
							<p><?php esc_html_e( 'This option will remove three resource hints automatically generated by WordPress, as of 4.8.2.', 'pprh' ); ?></p>
						</td>
					</tr>

					<tr>
						<th><?php esc_html_e( 'Send resource hints in HTML head or HTTP header?', 'pprh' ); ?></th>

						<td>
							<select id="pprhHintLocation" name="pprh_html_head">
								<option value="true" <?php echo Utils::get_option_status( 'pprh_html_head', 'true' ); ?>><?php esc_html_e( 'HTML &lt;head&gt;', 'pprh' ); ?></option>
								<option value="false" <?php echo Utils::get_option_status( 'pprh_html_head', 'false' ); ?>><?php esc_html_e( 'HTTP Header', 'pprh' ); ?></option>
							</select>
							<p><?php esc_html_e( 'Send hints in the HTML &lt;head&gt; or the HTTP header.', 'pprh' ); ?></p>
						</td>
					</tr>

					<?php do_action( 'pprh_sc_general_settings' ); ?>

					</tbody>
				</table>
			</div>
		</div>
		<?php
//		apply_filters( 'pprh_sc_pro_settings', 'general' );
	}

}

?>